apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    tier: prometheus
spec:
  ports:
    - port: 9090
      name: prometheus
  selector:
    app: prometheus
    tier: prometheus
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
    scrape_configs:
      - job_name: "prometheus"
        static_configs:
          - targets: ["localhost:9090"]
      - job_name: "mysql"
        static_configs:
          - targets: ["mysqld-exporter:9104"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app: prometheus
    tier: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
      tier: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prometheus
        tier: prometheus
    spec:
      containers:
      - image: prom/prometheus:v2.45.0
        name: prometheus
        ports:
        - containerPort: 9090
          name: prometheus
        volumeMounts:
        - name: config
          subPath: prometheus.yml
          mountPath: "/etc/prometheus/prometheus.yml"
          readOnly: true
        resources:
          limits:
            memory: 1G
      volumes:
      - name: config
        configMap:
          name: prometheus-config

